services:
  - type: web
    name: MoveEnglish
    env: java
    plan: free
    buildCommand: ./gradlew build && cp build/libs/*SNAPSHOT.jar app.jar
    startCommand: java -jar app.jar
    envVars:
      - key: BOT_ADMIN_ID
        sync: false
      - key: BOT_NAME
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_USERNAME