spring.application.name=MoveEnglish

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=false
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/moveenglish}
spring.datasource.username=${DB_USERNAME:move_user}
spring.datasource.password=${DB_PASSWORD:move_pass}

bot.name=${BOT_NAME}
bot.token=${BOT_TOKEN}
bot.adminId = ${BOT_ADMIN_ID}